image: openjdk:11

stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew shadowJar
    - mv ./build/libs/sheepit-client-all.jar ./
  artifacts:
    name: "$CI_COMMIT_REF_NAME-sheepit-artifact"
    paths:
      - ./sheepit-client-all.jar
    expire_in: 1 week

test:
  stage: test
  script:
    - ./gradlew check
